from label import get_sentiment
from visualize import make_plot

import json


def run(filepath: str):
    """
    function takes in a filepath and runs it through get_sentiment and make_plot to get OpenAI to
    read reviews and out a sentiment for each that will then be catergorized and displayed in a bar
    chart.

    filepath: run will take an input of a filepath in the format of a string

    returns: a graph of the sentiments generated by the review responses. 
    """
   
    # open the json object
    with open('data/raw/reviews.json') as j:
        d = json.load(j)

    # extract the reviews from the json file
    reviews = list(d["results"])
   
    # get a list of sentiments for each line using get_sentiment
    review_sentiment = get_sentiment(reviews)

    # plot a visualization expressing sentiment ratio
    plot = make_plot(review_sentiment)
    print("\n".join(review_sentiment))
    # return sentiments
    return plot
    


if __name__ == "__main__":
    print(run("data/raw/reviews.json"))


  
